name: Run and Deploy

on:
  push:
    branches:
      - main

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run script
        run: python script/first.py
